name: 'Inspect the Docker Image using Dive'
description: 'Build the container'
inputs:
  dockerimage:
    description: 'Container to scan'
    required: true
    default: 'container:latest'
outputs:
  report:
    description: 'The results of the Docker build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # image: 'docker://wagoodman/dive:latest'
  args:
    - ${{ inputs.dockerimage }}
    - '--ci'
    - '--json=diveReport.json'
    # - '--highestUserWastedPercent "0.5"'
    # - '--lowestEfficiency "0.8"'
    # - '--highestWastedBytes "100000000"'
