name: Build-Test-Deploy-Pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Images
      run: docker build -t ruby:2.6.5 .

    - name: Run the Dive utility
      uses: jaydeland/gha_dive@master
      with:
        dockerimage: ruby:2.6.5

    - name: Dive Report
      run: sudo apt-get install -y tree && tree && cat diveReport.json
